Repository mvfsillva/dialetus, pull requests merged in 2019-02, with the labels that each got.

#36 patch: config enzyme
  config/enzyme.setup.js
  config/enzyme.theme.js
  config/test/enzyme.setup.js
  config/test/enzyme.theme.js
Labels: 🐛 Type: Patch, 🤘 Priority: High

#37 patch: adjustment on jest config and upgrade pkgs
  .babelrc
  package.json
  yarn.lock
Labels: 🐛 Type: Patch, 🤘 Priority: High

#38 patch: theme primary color
  theme/default.js
Labels: 🆒 Priority: Low, 🐛 Type: Patch

#39 minor: component-header
  components/header/index.js
  components/header/index.spec.js
  pages/index.js
Labels: 🚧 Status: WIP, 🛠 Type: Minor, 🤘 Priority: High

#40 minor: component footer
  components/footer/index.js
  components/footer/index.spec.js
  pages/index.js
Labels: 🛠 Type: Minor, 🤘 Priority: High

#41 patch: add styled-enzyme
  components/footer/index.spec.js
  components/header/index.spec.js
  config/styled-enzyme.js
Labels: 🆒 Priority: Low, 🐛 Type: Patch

#42 minor: layout page
  layouts/default/index.js
  layouts/default/index.spec.js
  layouts/section.js
  pages/index.js
  styles/flex-center.js
  styles/full-container.js
  styles/main.js
Labels: 🙏 Priority: Medium, 🛠 Type: Minor

#35 major: add new interface
  .babelrc
  components/arrow/index.js
  components/arrow/index.spec.js
  components/brazil/assets/brazil-svg.js
  components/brazil/index.js
  components/brazil/index.spec.js
  components/card/index.js
  components/card/index.spec.js
  components/footer/index.js
  components/footer/index.spec.js
  components/header/index.js
  components/header/index.spec.js
  components/page-title/index.js
  components/page-title/index.spec.js
  components/search/index.js
  components/search/index.spec.js
  components/spinner/index.js
  components/spinner/index.spec.js
  config/enzyme.setup.js
  config/enzyme.theme.js
  config/styled-enzyme.js
  config/test/enzyme.setup.js
  config/test/enzyme.theme.js
  containers/list-card/index.js
  containers/list-card/index.spec.js
  icons/search.js
  layouts/default/index.js
  layouts/default/index.spec.js
  layouts/section.js
  package.json
  pages/about/index.js
  pages/dialect/index.js
  pages/index.js
  readme.md
  styles/flex-center.js
  styles/full-container.js
  styles/main.js
  theme/default.js
  theme/global-style.js
  utils/either/index.js
  utils/either/index.spec.js
  utils/if/index.js
  utils/if/index.spec.js
  yarn.lock
Labels: ⚠️ Type: Major, 🤯 Priority: Critical

#49 patch: add fallback when the dialect does not have examples
  components/card/index.js
Labels: 🐛 Type: Patch, 🤯 Priority: Critical

#50 patch: fix linter
  components/navigation/index.js
  components/navigation/index.spec.js
  components/search/index.js
  config/enzyme.setup.js
  config/enzyme.theme.js
  package.json
  pages/index.js
  routes.js
  theme/default.js
  yarn.lock
Labels: 🐛 Type: Patch

#55 patch: add links
  components/footer/index.js
  components/header/index.js
Labels: 🐛 Type: Patch
